/**
 * This file was automatically generated by @cosmwasm/ts-codegen.
 * Adapted for in-repo use.
 */

export type Addr = string;
export type Uint128 = string;
export interface Config {
  admin: Addr;
  chunk_execution_fee?: Coin | null;
  gas_fee_per_chunk: Coin;
  keeper_address: Addr;
  max_chunks_per_order: number;
  router_address: Addr;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg =
  | {
      create_twap_order: {
        ask_denom: string;
        chunk_count: number;
        max_spread?: Decimal | null;
        min_receive?: Uint128 | null;
        offer_denom: string;
        operations: OroSwapOperation[];
        pair_address?: string | null;
        total_amount: Uint128;
        total_time_minutes: number;
      };
    }
  | {
      cancel_order: {};
    }
  | {
      mark_chunk_failed: {
        chunk_id: number;
      };
    }
  | {
      execute_chunk: {
        chunk_id: number;
        user: Addr;
      };
    }
  | {
      cleanup_cancelled_order_chunks: {
        user: Addr;
      };
    }
  | {
      clear_reply_context: {};
    }
  | {
      update_config: {
        config: ConfigUpdate;
      };
    }
  | {
      emergency_pause: {
        paused: boolean;
        reason?: string | null;
      };
    }
  | {
      execute_trigger_ready_chunks: {};
    };
export type Decimal = string;
export type AssetInfo =
  | {
      native_token: {
        denom: string;
      };
    }
  | {
      token: {
        contract_addr: string;
      };
    };
export type PairType =
  | {
      xyk: {};
    }
  | {
      custom: string;
    };
export interface OroSwapOperation {
  ask_asset_info: AssetInfo;
  offer_asset_info: AssetInfo;
  pair_address: string;
  pair_type: PairType;
}
export interface ConfigUpdate {
  admin?: string | null;
  chunk_execution_fee?: (Coin | null) | null;
  gas_fee_per_chunk?: Coin | null;
  keeper_address?: string | null;
  max_chunks_per_order?: number | null;
  router_address?: string | null;
}
export interface InstantiateMsg {
  admin: string;
  chunk_execution_fee?: Coin | null;
  gas_fee_per_chunk?: Coin | null;
  keeper_address: string;
  max_chunks_per_order?: number | null;
  router_address: string;
}
export type QueryMsg =
  | {
      config: {};
    }
  | {
      order: {
        user: Addr;
      };
    }
  | {
      user_orders: {
        limit?: number | null;
        user: Addr;
      };
    }
  | {
      active_orders: {
        limit?: number | null;
        start_after?: Addr | null;
      };
    }
  | {
      chunk: {
        chunk_id: number;
        user: Addr;
      };
    }
  | {
      user_chunks: {
        user: Addr;
      };
    }
  | {
      stats: {};
    }
  | {
      user_stats: {
        user: Addr;
      };
    }
  | {
      pending_executions: {
        limit?: number | null;
      };
    }
  | {
      reply_context: {};
    }
  | {
      user_latest_order: {
        user: Addr;
      };
    }
  | {
      user_all_orders: {
        user: Addr;
      };
    };
